# Generated by Django 4.2.1 on 2023-05-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ratting',
            new_name='rating',
        ),
    ]
