# Generated by Django 4.2.1 on 2023-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=10)),
                ('descreption', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tender',
            name='descreption',
            field=models.CharField(max_length=100),
        ),
    ]
