# Generated by Django 4.2.1 on 2023-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_progress_alter_tender_descreption'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='progress',
            new_name='create_progress',
        ),
        migrations.RenameField(
            model_name='create_progress',
            old_name='t_id',
            new_name='t_Id',
        ),
    ]
